name: Reviews

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: set up code
    
    - uses: docker/login-action@v1
      name: Login to github registry
      with:
          registry: ghcr.io
          username: pungpeee
          password: ${{ secrets.TOKEN_GITHUB__BP }}
      
    - uses: docker/build-push-action@v2   
      name: Build images
      with:
       file: ./Dockerfile
       push: true
       tags: ghcr.io/pungpeee/bookinfo-reviews
       
  deploy:
    
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login ssh to remote server
      - uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.HOST }}
           username: Pungpeee
           password: ${{ secrets.PASSWORD }}
           script: |
            docker pull ghcr.io/pungpeee/bookinfo-reviews
            docker build -t ghcr.io/pungpeee/bookinfo-reviews .
            docker images
            docker run -d -p 9080:9080

